### ISSUE TITLE
"All mobs and eggs" wher tf are the ghasts

### ISSUE THREAD

**Issue by EPICSAURUSS** [realfreehij/Festival#8]
Im no dev, but ghasts 1 million percent are in 0.11 and it would be super cool and swag if you made them work on dis pocketmine fork plz and ty

proof im not trolling:
![image](https://github.com/user-attachments/assets/0b636b92-0580-4b3b-97f4-e4f32a67c94d)
https://youtu.be/v0Nsl52QcPo?feature=shared&t=35
https://youtu.be/QEH786dJT5Y?feature=shared&t=344

**Comment by GameHerobrine** [comment]
![Screenshot_20241002-123350_Minecraft_-_Pocket_Edition](https://github.com/user-attachments/assets/6fd7e5d7-82c4-47a0-9959-df24bd2de1bb)
There is no ghast spawn egg as an item in creative menu in 0.11.1, so it is not in this fork too. I suppose i could add ghast entity later(if it wasnt removed from 0.11 and can be spawned using some entity id ofc).

**Comment by GameHerobrine** [comment]
fixed in [c2b37c5](https://github.com/realfreehij/Festival/commit/c2b37c559f912a2dd8c0b97fcb62b4ba24210810)
